/** Append a GraphProto output without decoding/copying the model's weight tensors.
 * Caller MUST verify the source against the pinned Compact SHA-256 first.
 * Field numbers are from the ONNX protobuf schema: ModelProto.graph=7,
 * GraphProto.output=12. The value-info is generated by export_durations.py.
 */
const OUTPUT = Uint8Array.from("0a182f656e636f6465722f4761746865725f6f75747075745f3012190a17080712130a11120f73657175656e63655f6c656e677468".match(/../g)!, hex => parseInt(hex, 16));
function varint(bytes: Uint8Array, start: number): { value: number; end: number } {
  let value = 0, shift = 0, end = start;
  while (end < bytes.length) {
    if (end >= bytes.length || shift > 49) throw new Error("Invalid ONNX protobuf varint");
    const byte = bytes[end++]; value += (byte & 127) * 2 ** shift;
    if (!(byte & 128)) return { value, end };
    shift += 7;
  }
  throw new Error("Truncated ONNX protobuf varint");
}
function encode(value: number): number[] {
  const bytes: number[] = [];
  do { const byte = value % 128; value = Math.floor(value / 128); bytes.push(byte | (value ? 128 : 0)); } while (value);
  return bytes;
}
export function exposeNativeDurations(model: ArrayBuffer, output = OUTPUT): ArrayBuffer {
  const bytes = new Uint8Array(model);
  let offset = 0;
  while (offset < bytes.length) {
    const tagStart = offset;
    const tag = varint(bytes, offset); offset = tag.end;
    const field = Math.floor(tag.value / 8), wire = tag.value & 7;
    if (wire === 2) {
      const size = varint(bytes, offset), end = size.end + size.value;
      if (end > bytes.length) throw new Error("Truncated ONNX protobuf field");
      if (field === 7) {
        const outputField = Uint8Array.from([98, ...encode(output.length), ...output]);
        const header = Uint8Array.from([...encode(tag.value), ...encode(size.value + outputField.length)]);
        const result = new Uint8Array(tagStart + header.length + size.value + outputField.length + bytes.length - end);
        result.set(bytes.subarray(0, tagStart));
        let write = tagStart;
        result.set(header, write); write += header.length;
        result.set(bytes.subarray(size.end, end), write); write += size.value;
        result.set(outputField, write); write += outputField.length;
        result.set(bytes.subarray(end), write);
        return result.buffer;
      }
      offset = end;
    } else if (wire === 0) offset = varint(bytes, offset).end;
    else if (wire === 1) offset += 8;
    else if (wire === 5) offset += 4;
    else throw new Error("Unsupported ONNX protobuf wire type");
  }
  throw new Error("Model has no graph");
}

export function exposePiperDurations(model: ArrayBuffer): ArrayBuffer {
  return exposeNativeDurations(model, Uint8Array.from("0a0e2f4365696c5f6f75747075745f30121a0a18080112140a0208010a0208010a0a120870686f6e656d6573".match(/../g)!, hex => parseInt(hex, 16)));
}
